/**
 * test/lint/eslint.config.mjs
 * Config ESLint flat para la extension.
 * Objetivo principal: no-undef en cada contexto (SW, content, panel)
 * para atrapar bugs como usar `window` dentro del service worker.
 */
export default [
  // Service worker (background.js): tiene self/chrome, NO window/document.
  {
    files: ["background.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        self: "readonly",
        chrome: "readonly",
        console: "readonly",
        importScripts: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        Promise: "readonly",
        URL: "readonly",
        Date: "readonly",
        Math: "readonly",
        Object: "readonly",
        Array: "readonly",
        Number: "readonly",
        String: "readonly",
        Boolean: "readonly",
        JSON: "readonly",
        Set: "readonly",
        Map: "readonly",
        Error: "readonly",
        isNaN: "readonly",
        isFinite: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { args: "none", caughtErrors: "none", varsIgnorePattern: "^_" }],
    },
  },
  // Content script + libs: navegador (window/document/chrome).
  {
    files: ["content.js", "lib/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        self: "readonly",
        chrome: "readonly",
        console: "readonly",
        location: "readonly",
        fetch: "readonly",
        FileReader: "readonly",
        Event: "readonly",
        InputEvent: "readonly",
        KeyboardEvent: "readonly",
        MutationObserver: "readonly",
        getComputedStyle: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        globalThis: "readonly",
        Promise: "readonly",
        URL: "readonly",
        Math: "readonly",
        Object: "readonly",
        Array: "readonly",
        Number: "readonly",
        String: "readonly",
        Boolean: "readonly",
        Date: "readonly",
        JSON: "readonly",
        Set: "readonly",
        isFinite: "readonly",
        isNaN: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLInputElement: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { args: "none", caughtErrors: "none", varsIgnorePattern: "^_" }],
    },
  },
  // Side panel.
  {
    files: ["sidepanel/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        chrome: "readonly",
        console: "readonly",
        Parser: "readonly",
        FileReader: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        Promise: "readonly",
        Object: "readonly",
        Math: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        String: "readonly",
        Array: "readonly",
        isFinite: "readonly",
        parseInt: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { args: "none", caughtErrors: "none", varsIgnorePattern: "^_" }],
    },
  },
];
